### ISSUE TITLE
Prediction: XX

### ISSUE THREAD

**Issue by justingeeslin** [CogTool-Modern/cogtool#62]
Sometimes when calculating a time the prediction is reported as xx. One expects a time for a skilled user to complete the task. 

![Screen Shot 2020-09-18 at 9 47 34 PM](https://user-images.githubusercontent.com/1075425/93657392-1eabc280-f9f8-11ea-98c1-a22bbd39fcf6.png)

**Comment by justingeeslin** [comment]
A quick search through the code for "XX" reveals the following comment. 

```
//  ""  means no task application or no computable script for algorithm
//  --  means the demo is valid and current, but not computed
 // (><) means result is being computed
//  NN  means computed and the demonstration is valid and current
//  XX  means the computation failed and the demo is valid and current
 //  ??  means the demonstration is invalid or script needs regeneration
```

In our case, the XX case , "the computation failed and the demo is valid and current".

**Comment by justingeeslin** [comment]
Attached is the CogTool project that reveals the XX.  For this same project, all is well on Catalina 10.15, but for 10.12 the XX is the result.

[SECOM Beta.cgt.zip](https://github.com/CogTool-Modern/cogtool/files/5249014/SECOM.Beta.cgt.zip)

**Comment by justingeeslin** [comment]
Adding the `APredictionResult` error lines to the tooltip of the cell reveals that CLISP not being installed may be the culprit.

![Screen Shot 2020-09-18 at 10 38 06 PM](https://user-images.githubusercontent.com/1075425/93658496-8adef400-fa01-11ea-82fe-540f70d155aa.png)

Is CLISP a dependency of CogTool? This seems odd since there's plenty of CLISP bundled inside of the app including a `lisp.run`.

**Comment by justingeeslin** [comment]
Installing CLISP solved this issue for me. 

<details>
<summary>Install CLISP</summary>

* `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null`
* `brew install clisp`

</details>

Will reopen if anyone else has this issue for a different reason.

**Comment by justingeeslin** [comment]
To be more specific, On the Mac, CogTool 1.4 and above looks for the MacPorts version of CLISP. I've attached a package on the 1.4 release that will install CLISP.

**Comment by PatrickonGH** [comment]
I installed CLISP as described, but have still the XX issue. Tested on Mac 10.15.7:
<img width="604" alt="2020-09-30_14-00-44" src="https://user-images.githubusercontent.com/72138089/94682517-5afaef00-0325-11eb-8853-5392350e227b.png">

**Comment by justingeeslin** [comment]
@PatrickonGH Earlier in the issue, I cited the Homebrew CLISP as the solution to this issue only find out later that the MacPorts version is actually the solution. 

Have you installed CLISP via MacPorts either by the package attached to the 1.4 release or via MacPorts CLI (I think 'port install clisp')?

**Comment by justingeeslin** [comment]
Additionally, we created an alpha release for debugging this very issue. 

https://github.com/CogTool-Modern/cogtool/releases/tag/1.5-alpha

In the cell Tooltips you'll find error messages as to why the computation failed. Please Try this alpha release and report back the contents of the cell tooltip with your setup if installing MacPorts CLISP doesn't solve the issue.

**Comment by PatrickonGH** [comment]
@justingeeslin Thanks! I installed the package and it works now. 

This is nevertheless somehow strange because I have a working CLISP installation on my computer. I would have thought that a symlink in the right place would be enough. 

It also seems that loading actr6.mem expects a specific version.

**Comment by justingeeslin** [comment]
Glad that fixed the issue for you!

Yes, you are correct; ACT-R in the form of a saved memory image does require the same CLISP that generated it. If we relied on the CLISP already installed it seems like we'd have to generate a act6.mem for that CLISP installation for that OS / Arch combo. 

I think the motivation for pre-generating a memory image in the first place was for performance reasons, but this decision was made back in the WinXP days, when an entire OS fit on a CD, less than 700 MB! 

That said, `actr6.lisp` (not `.mem`) is included in CogTool and I wonder if it would be to our advantage to load `actr6.lisp` in memory at runtime, for portability reasons. Then maybe we could rely on a system with CLISP already installed.

**Comment by PatrickonGH** [comment]
That would be worth a try. It may also be possible to get the last stable release of ACT-R when ANT is running.

**Comment by justingeeslin** [comment]
Ah, Good idea!
